### ISSUE TITLE
Add litter box

### ISSUE THREAD

**Issue by emtrimble** [scott-joe/dreamland#13]

**Comment by scott-joe** [comment]
Hopefully something bigger than what we've got now. Even as a 5mo kitten, he seems like he's too big for what he's got now. Oh man, I wonder if I could build a litter box with a bottom that'd slide out and get scraped off as you pull it out to expose a mesh below to catch all the mess, leaving the "clean" litter to fall through to a reservoir below and once the plate is returned, dump it back in the top. Basically a self-scooping littler box.

Then all you'd have to do is dump the top part with the mesh captured mess into a bin.

**Comment by scott-joe** [comment]
We bought the Pet House Litterbox from Hayneedle
http://www.hayneedle.com/product/catwashroomnightstandpethouse.cfm
![image](https://cloud.githubusercontent.com/assets/2026866/19223019/7e52119c-8e33-11e6-9736-9d659303b603.png)

**Comment by emtrimble** [comment]
I assembled this on Friday and Rudy loves it! The shelves are nice too, so we can put towels for guests on top.
