### ISSUE TITLE
Window coverings

### ISSUE THREAD

**Issue by scott-joe** [scott-joe/dreamland#14]
Looking at window coverings for the entire house

**Comment by scott-joe** [comment]
## 1st findings:
Lowes had some good things. One company that we already ordered samples from is Levolor. They had two styles of shades that seemed to be close to what we'd want. There's one model that's good for privacy and helps with heating/cooling costs called Cellular Shades. It essentially creates a honeycomb chain of pleated air pockets that you simply lift and it stays in place.

The other style was Roller Shades. They're a very thin shade that rolls up into a top unit via drawstring. They're a little more expensive, so we ordered samples of each style in a number of different colors.

### Cellular Blinds
![image](https://cloud.githubusercontent.com/assets/2026866/19222769/1a0769bc-8e2e-11e6-8fae-5f0f0e80a457.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222772/282e722e-8e2e-11e6-92e1-617f8c38def7.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222775/3253ab70-8e2e-11e6-9527-1b2fc9d82025.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222776/3759daa4-8e2e-11e6-8efe-a68eb5018e4a.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222777/3af2e8b8-8e2e-11e6-9b06-3dd27501cbee.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222780/3fe29dfa-8e2e-11e6-9214-6765f3054e5c.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222784/438918c6-8e2e-11e6-9c76-d04e72cba016.png)

### Roller Blinds
![image](https://cloud.githubusercontent.com/assets/2026866/19222855/2d10126e-8e30-11e6-8b8b-b16cbdd48c0e.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222857/3aea74d8-8e30-11e6-86ce-85aa0ff95862.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222858/3e682e52-8e30-11e6-9d8c-72d6a712160f.png)
![image](https://cloud.githubusercontent.com/assets/2026866/19222859/4207eac0-8e30-11e6-8274-92a8563cebd1.png)

**Comment by scott-joe** [comment]
http://lowes.levolor.com/products/blinds-shades.html

This covers most of the blinds we were looking at

**Comment by scott-joe** [comment]
My rough rough rough estimates put this at about $1300 for all the windows in the house. If we cut out some of the high wide windows above other windows, we could probably get away with less.

**Comment by emtrimble** [comment]
Like the Cellular Shades, color Tumbleweed. 

Measuring on Tuesday, October 18, to place order. 

- Living room picture window
- Dining room windows (2)
- Kitchen window
- Entry-way window
- Bedroom windows (2)

**Comment by emtrimble** [comment]
We spent about $1600 on the shades, and my Dad installed them for free. One was the wrong size, so we'll have to send it back. Otherwise they look great!
![img_0555](https://cloud.githubusercontent.com/assets/13732176/20072888/3278e26a-a4f8-11e6-9083-da91aa91fc4b.JPG)
![img_0556](https://cloud.githubusercontent.com/assets/13732176/20072889/32dab62a-a4f8-11e6-88a7-6646a1d87014.JPG)
![img_0557](https://cloud.githubusercontent.com/assets/13732176/20072887/327683c6-a4f8-11e6-91bb-ec1c07318579.JPG)
